### ISSUE TITLE
Add Canadarm Demo

### ISSUE THREAD

**Issue by tonylitianyu** [space-ros/demo#7]
The Canadarm Demo is ready, we have multiple demos now. A temp solution is to add the Canadarm demo parallel to the Curiosity demo.

**Comment by kryptoniancode** [comment]
I have build and source it but getting this error.

```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: "package 'simulation' not found, searching:
```

Also got error about `xacro`, so intalled using.
```
pip install xacro
```

So, how to run this demo in docker image?
